### ISSUE TITLE
Deleted requests don't remove the comments

### ISSUE THREAD

**Issue by vixriihi** [DiSSCo/ELViS#118]
#### Description
When I delete a request the comments added to it are not
https://elvis-accept.pictura-hosting.nl/calls/7d4cc4af-ac72-406e-b128-0edb23e48659/new-request/5a0465ae-8813-4bc1-95b3-0459fc4449ef

#### Steps to reproduce the issue

1. add a request
2. add a comment to it
3. copy the url
4. delete the request from "My reqests"-page
5. go to url copied at step 3

#### What's the expected result?
- empty request with no comments

#### What's the actual result?
- empty request with the comments added to it

#### Additional details / screenshot
![image](https://user-images.githubusercontent.com/5203261/83836224-836a3800-a6fb-11ea-9063-951cc47c6a1b.png)

**Comment by cannedit** [comment]
I don't think this is a real issue, because:
* the comments section is only meant for communication between a requester and a VA Coordinator AFTER a request has been "submitted", so in this stage using the comments section is basically creating a "note to self"
* in case we block accessing a draft request by copying the url to it, this can't be reproduced (see Github issue 116)
