### ISSUE TITLE
do we need a separate first name + last name?

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#12]
#### Description
I am not sure if we need a separation in first name and last name. Only benefit I can think of is sorting a user listing for an admin. Drawback is that it does not take into account people with multiple names or name parts internationally. For example a typical Spanish name consists of four parts: First name, second first name, father's last name, and mother's last name. A Dutch last name can have multiple parts like van der Heijden, which should be sorted on Heijden, etc.

**Comment by AnniinaK** [comment]
In FinBIF we used to have one field for all names but it turned out to be a better solution to have two separate fields (there were cases where we needed to use only last name, also easier to recognise which of the names is first and last). We think the first field should be "First name(s)" instead of just "Name" and the second maybe "Last name" or "Surname" or "Family name".

**Comment by cannedit** [comment]
During our meeting on the 7th of January we decided to leave the two name fields for now (for the MVP ELViS), but to change "Name" into "First name"

this ticket is added in Redmine as issue #46709
https://code.pictura-dp.nl/issues/46709
