### ISSUE TITLE
version number not changed

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#120]
#### Description
A minor issue: I would have expected the version number displayed at the bottom of the page to be increased from the previous release.

**Comment by cannedit** [comment]
This is a bit arbitrary, because normally production server versions get increased numbers, otherwise - with multiple test server and acceptance server deployments prior to a production server deployment - there will be gaps in the numbering on the production server; nevertheless I registered this in Redmine to at least be taken care of during the next production server release: https://code.pictura-dp.nl/issues/49602

**Comment by wouteraddink** [comment]
solved.
