### ISSUE TITLE
new request is not saved until after new login

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#124]
#### Description
after entering a title and hitting enter to start a new request, nothing happened (the rest of the form was not shown). It worked after new login. Probably related to still being logged in from previous deployment. This will create problems when it will be deployed on production too. Somehow login of users already logged in should be refreshed after new deployment (or if not possible they should be logged out with new deployment, but that could create problems with people working on a request at the time of deployment).

**Comment by vixriihi** [comment]
I had this issue even after login.
Today I first logged in and then tried to test this issue https://github.com/DiSSCo/ELViS/issues/115

**Comment by cannedit** [comment]
The behaviour as mentioned here originally, is mainly due to people not logging out when they are done working in ELViS, so that causes problems with new functionality not kicking in properly when they start using ELViS again. We are aware of the fact that this can also cause problems when we do a new deployment when people are still working in ELViS, but we will try to avoid that when performing the upcoming deployment on production.

**Comment by B-San-Chi** [comment]
As a requester, with a different email account as VA coordinator, I have filled the empty fields without problem but it is not possible to save it. The button to update it continues "thinking"

**Comment by B-San-Chi** [comment]
I had logging out because if not I can not work as a requester (only VA coordinator), the fields filled 5 minutes ago are saved but I have push again the update button and keep thinking

**Comment by cannedit** [comment]
This has now been solved on the Acceptance server
