### ISSUE TITLE
Multiple entries with the same facility name

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/ELViS#156]
#### Description
I was able to create multiple entries for a facility with the same name. 

#### Steps to reproduce the issue

1.  Logged as Moderator
2. Went to NHM 
3. Clicked on Create New Facility 
4. Added a new facility called (MBU)
5. Added a instrument 
6. Save
7. Click Create New Facility Again 
8. Added the same facility name as in step four (MBU) 
9. Add another instrument 
10. Save

#### What's the expected result?

Expected to get an error that name already exists. 

#### What's the actual result?

It allows to create new facility with the same name. 

#### Additional details / screenshot

![image](https://user-images.githubusercontent.com/50382675/102795606-53d80000-43ad-11eb-9563-50d9de7e1c9e.png)

**Comment by cannedit** [comment]
I am not sure whether we should be strict on this, because basically the combination of a facility name and the name of the institution/country to which it is connected makes it unique; and as for instruments and services: it's of course possible that different institutions use the same equipment (brand, model), so let's not force them to 'invent' another unique name.
