### ISSUE TITLE
Instruments and services not searchable 

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/ELViS#157]
#### Description

(probably an enhancement request). Currently only facilities names are searchable. It would be useful to search by the instrument name as well. 

List of facilities: 

![image](https://user-images.githubusercontent.com/50382675/102796914-3f950280-43af-11eb-84e9-15903052e4e5.png)

Search for the text "3D"

![image](https://user-images.githubusercontent.com/50382675/102796812-1c6a5300-43af-11eb-81ca-0d85787f8bb3.png)

**Comment by cannedit** [comment]
This will become available later on, just like searching on the local name (https://github.com/DiSSCo/ELViS/issues/150) .

**Comment by cannedit** [comment]
Searching for "Instruments & services" is now available, please test.

**Comment by emhaston** [comment]
This works. Would be good to change the help text in the box to : Search for Facilities and Instruments by name

![image](https://user-images.githubusercontent.com/6713716/106587513-a0346500-6541-11eb-828d-c1fd591432c2.png)

**Comment by philippeloret** [comment]
This works. We can search by instruments, services, country but not by institution acronym (i.e MNHN or RBGE)

**Comment by cannedit** [comment]
Hi @emhaston,
Ok, that might be an enhancement for later on (officially it then would have to be: "Search for Facilities and Instruments & services by name" and that would be too long and would technically also have to be changed into "by keywords"). Let's leave this for now, because Instruments & services are part of Facilities. I will make sure this gets mentioned in the manual (actually it is already mentioned in the manual).
 
Hi @philippeloret,
Ok, that might be dealt with later on, so a furthere enhancement.

The issue itself is resolved so I hereby close this ticket.
