### ISSUE TITLE
maximum number of characters

### ISSUE THREAD

**Issue by mmarschler** [DiSSCo/ELViS#165]
For requesters, it is very helpful to see the maximum length (number of characters) in each section of the request. So either the information about the maximum number of characters should be given, or alternatively some kind of "character counter" at each section of the TA/VA request should be implemented.

**Comment by mmarschler** [comment]
Just saw that this is already on the agenda.

**Comment by scottwilson-nhm** [comment]
Thank you Maria - agreed, this should be visible next to each of the text fields if possible.

**Comment by cannedit** [comment]
Yes, that will be information provided in the 'sticky' blue info box (available after the next Acceptance server deployment).

**Comment by cannedit** [comment]
This is now available, please test.

**Comment by mmarschler** [comment]
The blue box is now implemented and can be seen by the requester. But there is only the first sentence shown ("All information you fill in here is stored in real time.") and the "more info"-button. As a new requester, I think that there is just more info about real time storage. But there are a lot of important informations like the limit of text fields or general informations about submitting a request. This could be more highlighted by adapting the wording: Instead of "more info" you could e. g. write "more info about the submitting process" or something like that.

**Comment by cannedit** [comment]
I understand you concern, but this is a compromise because we not only have to show the blue box, but also the navigation flow. I guess the ELViS users will be smart enough to find the info and of course we can explain everything in more detail in the manual. And unfortunately we are still having a lot other - imho more important - things to take care of before the deadline first.
