### ISSUE TITLE
TA: Supporting statement

### ISSUE THREAD

**Issue by mmarschler** [DiSSCo/ELViS#172]
The sentence "_It is acknowkledged that for PhD students this will be difficult to attain._" is quite confusing, since the supporting statement was mandatory in call 1 & 2.

**Comment by cannedit** [comment]
This text is provided to us and - as far as I know - derived from the 'old' Synthesys tool. It was part of the wireframes for the TA Call Request form, which were approved by the Synthesys WP6 community. Since the supporting statement is not mandatory in the ELViS TA Call Request form, I guess this is not much of an issue?

**Comment by cannedit** [comment]
There is a new text provided and updated, please test.

**Comment by mmarschler** [comment]
Ok now! Thx!
