### ISSUE TITLE
 adding other team members in request

### ISSUE THREAD

**Issue by LarissaS** [DiSSCo/ELViS#179]
#### Description
I was editing my draft request and I see that “i-icon”  is missing for "user team leader" 
Also may be it should be added in the i-text that you only can add researches if they are already registered in the system, if not you have to register them first.
#### Steps to reproduce the issue

1.  
2. 
3. 

#### What's the expected result?

-

#### What's the actual result?

-

#### Additional details / screenshot

![image](https://user-images.githubusercontent.com/949726/106755716-bc620000-662e-11eb-85fb-ebeda9a95c8f.png)

**Comment by cannedit** [comment]
Hi @LarissaS,
That's correct, the i-icons that should be there are missing; this is a bug which we will solve soon; however, please check the i-icon texts in the manual, these are the texts that are agreed upon with NHM/London; in case texts need to be changed, please contact them, because they are still providing a list of missing texts, so we can process those in one run.

**Comment by cannedit** [comment]
This is fixed now, please test.

**Comment by philippeloret** [comment]
Tested, i-icons are now visible.
