### ISSUE TITLE
"My requests" is now "Show only requests for my institution"?

### ISSUE THREAD

**Issue by LarissaS** [DiSSCo/ELViS#182]
#### Description
as a requester I'm searching for my request. I expected to see two options:" Show all request" and "Show my requests". Instead, the last one is now "Show only requests for my institution". I would expect this option for a TA moderator, but not for a requester.
 

#### Steps to reproduce the issue

1.  
2. 
3. 

#### What's the expected result?

-

#### What's the actual result?

-

#### Additional details / screenshot
![image](https://user-images.githubusercontent.com/949726/106876686-44e8ab00-66d8-11eb-8cb6-ae95a57378e3.png)

**Comment by mmarschler** [comment]
That's curious. I still have "Show only my requests".

**Comment by LarissaS** [comment]
I think that happened after I changed from "coordinator" account to "requester"

**Comment by mmarschler** [comment]
We just found out that this is a problem of "double roles". My colleague Andrea has the roles "requester" and "TA coordinator", and she also can only filter "Show only requests for my institution" (which does not work properly, see #188). 
![ELViS_requests_my_inst_AS_2021-02-08](https://user-images.githubusercontent.com/75616869/107226397-5dc7c800-6a1a-11eb-8d49-ca6c69a43ef9.PNG)

**Comment by cannedit** [comment]
This is fixed now, please test.

**Comment by LarissaS** [comment]
It's ok now.  
But is it normal that I can open requests from other people and read a content?

**Comment by cannedit** [comment]
For VA Requests: yes, that's an agreement made within the project a long time ago.

**Comment by cannedit** [comment]
This has been taken care of, please test.

**Comment by LarissaS** [comment]
I see nothing from TA call, only two VA projects. One of them is NOT for RMCA.

**Comment by cannedit** [comment]
@LarissaS can you please provide screenshots and indicate what you are expecting to see and in what role?

**Comment by LarissaS** [comment]
As a TA coordinator I see 12 request, 4 are not for RMCA (e.g.: from Wim and Jonas) 
![image](https://user-images.githubusercontent.com/949726/110486802-48af8900-80ed-11eb-86c9-93db87a07c38.png)
As inst. coordinator (and TA and VA coordinator)  I see only two VA projects:
![image](https://user-images.githubusercontent.com/949726/110487088-86141680-80ed-11eb-8620-a37c999d8f34.png)

**Comment by cannedit** [comment]
I see only 2 requests not belonging to your institution in your first screenshot:
* Just another TA Call request - this one belongs to Agentschap Plantentuin Meise
* My test ta request - this one belongs to Schenkenberg
The other one - New Repo Test - has two institutions involved: Agentschap Plantentuin Meise and RMCA:
![NewRepoTest](https://user-images.githubusercontent.com/22167327/110497879-23c01380-80f7-11eb-8302-c94674a4de68.png)

I can't really explain why the two others are in your overview, but these are from before we refactored the filtering, so probably something went wrong earlier with these two. But this will not occur in the Production server, simply because that server will not contain any 'old' TA requests, so from older ELViS versions.

As for only seeing VA requests when logged in as Institution Moderator: that's normal behaviour, because Institution Moderators are not involved in TA requests, so are not allowed to see then according to the new rules.

**Comment by cannedit** [comment]
See also Github issue #203
