### ISSUE TITLE
two fields  "amount of days" under the same facility

### ISSUE THREAD

**Issue by LarissaS** [DiSSCo/ELViS#198]
#### Description

For Musee Royal d'Afrique central under facility "Molecular Lab Facilities" there are two fields 'amount of days'. Under other facilities, also if you choose two institutions, there is always one field. 

#### Steps to reproduce the issue

1.  create new request
2. choose MRAC as host institution
3. go to "Resources needs"
4. under "Molecular Lab Facilities" you see two dropdown fields 

#### What's the expected result?

-

#### What's the actual result?

-
![image](https://user-images.githubusercontent.com/949726/108074253-48c9e500-7069-11eb-9c25-98dfb1c5b78b.png)

**Comment by jgrieb** [comment]
I think this is not a but error. This is because of the entered facilities data for MRAC. If you go to https://elvis-accept.pictura-hosting.nl/institutions/grid.425938.1/facilities/13e62962-fd78-48ba-818d-3d728270bbe8 you see that there are two "Instrument or service" entries but without names. The 'Amount of days' fields in the form are for each individual instrument or service. You just need to edit the names of the instruments as institution moderator, then they get displayed in the TA request form.

**Comment by LarissaS** [comment]
I can't see that there are two instruments there! Actually I can't  update my facilities at all. I understand that we are not allowed to delete facilities, but why not to update them? if for example there are any errors, or I want to add something (an photo, url,  description).

**Comment by cannedit** [comment]
I checked and @jgrieb is right (see the video attached); the idea is that facilities should be fully up to date before a TA Call starts, so when a TA Call starts no editing/deleting of facilities is possible anymore, only adding facilities and the latter only in case of an emergency in case an Institution Moderator forgot to add a facility which might block a visit. Sorry, but these are the rules that we agreed upon.

https://user-images.githubusercontent.com/22167327/108870111-1fc0cb80-75f8-11eb-8693-277e48e7277b.mp4
