### ISSUE TITLE
TA request visible which is not assigned for my institution

### ISSUE THREAD

**Issue by mmarschler** [DiSSCo/ELViS#203]
#### Description
In the list of requests assigned to my institution (NHMW), there is one TA request that is not assigned to NHMW, but for Senckenberg. 

Requests assigned to me:
![2021-02-18_ELViS_instmod_assignedrequests](https://user-images.githubusercontent.com/75616869/108408966-f41f9900-7225-11eb-80ba-48a71b1c2079.JPG)

Details of TA request which is wrongly shown in my list:
![2021-02-18_ELViS_TA_JGrieb](https://user-images.githubusercontent.com/75616869/108409098-174a4880-7226-11eb-9498-27dd187c51b9.JPG)

**Comment by LarissaS** [comment]
the same, from 9 assigned requests 3 are not for RMCA.

**Comment by cannedit** [comment]
Apparently something went wrong with Jonas' request, see also Github issue #182.

I can't really explain this other than that this is probably caused by using different versions of ELViS for looking at TA requests in combination with the recent refactoring the filtering as well as the assigning of roles.

However, I don't expect this to pop up in the ELViS Production server, because over there we will not be dealing with legacy TA requests from 'older' ELViS versions.
