### ISSUE TITLE
All the filled out fields in my TA request dissapear (forever?) if i attempt to change the "institution to visit" field after the reqest is submitted 

### ISSUE THREAD

**Issue by lenarulz** [DiSSCo/ELViS#224]
If i try to change the "insitution to visit" in my own TA request, the system allows me to choose from the drop down menu and change it, however after i click save (or something similar), all the fields below simply disspear and it remains like that even if i go back to the list of requests and open my own request again.

#### Steps to reproduce the issue

1.  Go to the list of the requests
2.  Click on your own TA request
3.  Change the "instituion to visit" and submit

#### What's the expected result?
Either no option to change the institution
or
A message that the change of insitution is not possilbe after the call is closed

#### What's the actual result?
All the fields filled out previously dissapiear
![fields dissapear](https://user-images.githubusercontent.com/79263858/110776557-7bc65980-8260-11eb-86e7-8261e996581e.JPG)

**Comment by cannedit** [comment]
That is normal behaviour as agreed upon: changing an institution in a TA request, means that you have to fill in all details for the request anew. This is because the connection between an institution and its resources (facilities) has to be shown in the form. So in case another institution is selected the accompanying info has to be shown, so then it's basically a new request.
