### ISSUE TITLE
The automatic saving of the request form seems to cause strange behavior

### ISSUE THREAD

**Issue by mtrekels** [DiSSCo/ELViS#35]
#### Description

In a specific test (condition of slow internet connection?, exact conditions not really known) it seems that the automatic saving of the entered text is preventing to type the next letter of a word (if typing above a certain speed). Also backspace seems to enter in a loop where the letter is removed, but reappears

#### Steps to reproduce the issue

1.  (condition of slow internet connection?)
2.  Start a new request
3. Start typing in the 'request subject' box

#### What's the expected result?

- text is entered smoothly

#### What's the actual result?

- letters are not appearing during the 'saving' process

**Comment by Karin-Wiltschke** [comment]
Next to the submit button Information should be provided, that the draft is automatically saved and a warning that you cannot Change anything when submitted.

**Comment by cannedit** [comment]
@mtrekels in my experience that only goes for the first item to fill in, the "Request subject" and that is due to the fact that at that moment a record is stored in the database; do you experience this also when entering information in other fields?

**Comment by cannedit** [comment]
@Karin-Wiltschke I guess the info that the draft is automatically saved can best be put at the start of filling in the form, rather than at the end of it? And the fact that you can not change anything anymore after submitting is only true for this test run; the idea is - for the MVP ELViS - that a requester can always go back to the form and change something, also after submitting, until all VA Coordinators have approved their part, then the request will be definitive

**Comment by mtrekels** [comment]
@cannedit indeed it seems to be only at the 'request subject' field

**Comment by cannedit** [comment]
@mtrekels Ok, so can we leave this as it is for now?

**Comment by mtrekels** [comment]
Is it technically difficult to solve? Because at the moment it is relatively annoying to fill out this field.

**Comment by cannedit** [comment]
If you say "relatively" I suggest we leave this as it is for now, because we already have a lot to deal with in order to meet the deadline ...

**Comment by cannedit** [comment]
@Karin-Wiltschke I will ask our developers to put in this text at the beginning of the form: 
"All information you fill in here is stored in real time, so you can always come back to this form and finish it at a later stage. Only after you hit the "Submit"-button at the end of the form the request gets forwarded to VA Coordinators for evaluation."
Are you Ok with this?
Registered in Redmine as issue 47491
https://code.pictura-dp.nl/issues/47491

**Comment by cannedit** [comment]
@mtrekels I have checked with the developers and they seem to have a solution for this, which will be implemented in the next version

**Comment by Karin-Wiltschke** [comment]
@cannedit 
Text is fine but
"Only after you hit the "Submit"-button at the end of the form the request gets forwarded to VA Coordinators for evaluation"
The VA-coordinater has to be involved from the beginning!

**Comment by cannedit** [comment]
@Karin-Wiltschke sorry, but that is not what we agreed upon for the MVP ELViS: once a requester has finished his/her request, the VA Coordinator gets to evaluate it and can get in touch with the requester via the comments functionality, which is not in place yet for this test version; after that, a VA Coordinator wil be able to approve or reject the request, so that is the final submit
