### ISSUE TITLE
New request - people involved

### ISSUE THREAD

**Issue by Karin-Wiltschke** [DiSSCo/ELViS#36]
http://elvis-accept.pictura-hosting.nl/calls/7d4cc4af-ac72-406e-b128-0edb23e48659/new-request

People involved:

what does this mean - cooperation Partners, or curators, or VA coordinator,...?

please specify and put it in a systematic way that it is trackable 

Name, Institution, ….

We need Information on the curator in charge in the form either in the People involved section but explicitely asked for or in Connection with the Collection requested.

**Comment by Karin-Wiltschke** [comment]
How/where can we add an additional requester to an existing or new proposal? This was an essential topic for the scoring (many People are interested in one Collection)

**Comment by cannedit** [comment]
@Karin-Wiltschke I understand that it's necessary to get additional requesters involved (that's what's meant here with "people involved"), but we decided that fetching those from the list is not in scope for the MVP, because they might not be registered yet, which would make creating this functionality a bit complicated for now; so I suggest just to change "people involved" into "Other requesters involved (name and email address)" or something like this, agreed?
Registered in Redmine as issue: 47500
https://code.pictura-dp.nl/issues/47500

**Comment by HMHardy** [comment]
There needs to be a distinction, as in the ideas call, between 'proposers' (who could be anyone and therefore no drop down list  possible) and 'digitising institutions' (who are in your dropdown, and for whom the contact should be the VA coordinator). 
This affects the 'institutions involved' page as well as the 'people involved' field - people involved field is perhaps not needed at all or should be replaced with a 'proposers' section which captures both names and institutions/contact details? Or the Institutions page needs to be in two stages for proposers and digitising institutions, both of which should allow multiple entries.
I think the system should first get the details of the lead/corresponding proposer (the requestor in your terms, probably?) - if this is known from their registration perhaps it could be pre-populated but still helpful to show this in the form so people can see it.

**Comment by Karin-Wiltschke** [comment]
HMHardys suggestion is optimal, but anyway we need a clear definition if we keep this field

**Comment by cannedit** [comment]
Given the amount of time left towards the deadline, I suggest we leave this field "People involved" out for now, agreed?

**Comment by HMHardy** [comment]
Yes but only if the next page can be changed to cover both proposers (or requesters if you prefer) and digitising institutions? It is essential to capture both sets of names/institutions, and to distinguish between them.

**Comment by cannedit** [comment]
I am sorry, but I don't understand this: when we leave out this field "People involved" then it's obvious that there are two entities in the request: the requester and the institutions involved and because the requester most likely will make a pick out of the list of institions, so will not select all institutions, hence the terme "institutions involved" (and the same goes for collections).

**Comment by HMHardy** [comment]
There can (should in many cases) be multiple 'requesters'/proposers, all of whom also have an institution, details of which we need to collect per the ideas call - so in other words there are two kinds of institutions or people involved and we need to be able to capture multiples of each, and to have them clearly distinguished - see also #43

**Comment by HMHardy** [comment]
Having multiple proposers/requesters is one of the ways to demonstrate community interest as opposed to individual interest

**Comment by cannedit** [comment]
Correct, but we will deal with this after the MVP ELViS, so for now we focus on getting the registration of requesters and requests up and running on the deadline date and possibly on the same date or shorty after, the handling of the requests via interaction between requesters and VA Coordinators

**Comment by wouteraddink** [comment]
I think much of the confusion is about the naming of the field. I would propose to rename it to **Other proposers**. Since requester as a term makes sense for ELViS as a whole but is confusing as long as there is only functionality for VA proposals, I would use the term proposers here (and only here). Plus a more info icon [i] with guideline how to fill this in: "please supply name, email address, affiliation and ORCiD for other proposers involved."
 If possible in the limited time there is, before this field there should be a line stating: **lead/corresponding proposer: [name fetched from logged in person making the request]**, name linking to their ORCiD url.

**Comment by cannedit** [comment]
I still think we should stick to the terms already agreed upon (in fact before the form for the preparation of the VA Call was drafted, so this didn't take the ELViS discussions into account) and it will be confusing to change "requester" into "proposer(s)" in just one place in the tool. This being said: I already asked the developers to change the label "People involved" into: "Other requesters involved (name, email address and ORCID)", so let's for now stick to this.

As for requests for explanation in various spots in the tool, we will take care of this, but we already decided to produce a short explanatory guideline for the tool which we can link to somewhere.
