### ISSUE TITLE
VA-coordinator-rights

### ISSUE THREAD

**Issue by Karin-Wiltschke** [DiSSCo/ELViS#38]
?? what are the optionsfor the VA-coordinator, can he edit the requests? Can he / she track the history of changes? 

Where is the VA-coordinator or more than one mentioned in the form

**Comment by cannedit** [comment]
For the MVP ELViS we have decided that a VA Coordinator can communicate with the requesters via making comments on the request (that functionality is not in place yet in this test version), after which the requester can make change or add information in the request; after the VA Coordinator is satisfied with the changes/additions made by the requester (so for now, for the MVP ELViS) only the requester can edit his/her request after submitting (this functionality is not in place yet in this test version either), a VA Coordinator can either approve or reject the part of the request for his/her institution. VA Coordinators come along with the institution information once the request is registered; this functionality is not in place yet for this test version.

**Comment by HMHardy** [comment]
Will VA coordinators be able to upload the cost template or does this also have to come via the requestor?

**Comment by Karin-Wiltschke** [comment]
The costbook can only be done from the institution therefore the VA-coodinator of this institution should upload it.

**Comment by cannedit** [comment]
Then in the current setup (for the MVP ELViS) the VA Coordinator should provide it to the requester and he/she should upload it.

**Comment by Karin-Wiltschke** [comment]
Dear Wim,
now I am completely confused: in your latest statment (from another issue) :
"@Karin-Wiltschke sorry, but that is not what we agreed upon for the MVP ELViS: once a requester has finished his/her request, the VA Coordinator gets to evaluate it and can get in touch with the requester via the comments functionality, which is not in place yet for this test version; after that, a VA Coordinator wil be able to approve or reject the request, so that is the final submit"

the VA-coordinator is not involved until the submit button is pressed. So how could he provide cost books and information?

**Comment by cannedit** [comment]
Via the comments system, and I assume that the requester will already have provided a costs calculation documents, so if that is the case the VA Coordinator will probably only have remarks and/or additions to the content of that document, so then the requester can take care of changing/adding that

**Comment by Karin-Wiltschke** [comment]
The cost calculations are done in the museums, not by the requester - Scott provided the new cost calculation sheet today for the VA coordinators. the information needed for this are not in the hands of the requester

**Comment by cannedit** [comment]
Hmmm, that was not specified to us like that and the fact that we were asked to provide a link to the template for these cost calculation documents on the VA Call's info page (see the related issue over here), suggests otherwise; anyway, since it's too late to change that now, it's best to - for now (for the MVP) - stick with the above mentioned workflow: only change is that the requester can't upload a costs calculation document until he/she has received that - via the comments system - from the VA Coordinator, agreed?

**Comment by cannedit** [comment]
Regarding the link for downloading the template for the Costs calculation document: I have just agreed with Wouter via a telephone conversation that the template will have to be put on the VA Call webpage of the Synthesys+ project, because - since apparently the requester is not the one to fill this in but the VA Coordinators - putting this up on the info page for the VA Call in ELViS will confuse requesters
