### ISSUE TITLE
Project title visible 

### ISSUE THREAD

**Issue by Karin-Wiltschke** [DiSSCo/ELViS#39]
the Project title (and Project number) should be visible on every page in the submitting process as Header and in every communication (mails) as a reference

**Comment by cannedit** [comment]
Registered as Redmine issue: 47497
https://code.pictura-dp.nl/issues/47497

**Comment by HMHardy** [comment]
The 'request type' field should perhaps be the 'project name' or ideally 'proposal name' field?
Will the system generate project numbers? If so i agree these should be immediately visible throughout

**Comment by cannedit** [comment]
Please let's not make any changes in terms at this stage for the MVP ELViS anymore (there is simply not enough time in case we need to meet the deadline), we already discussed some time ago to go for "requesters" and "requests" for now.

As for request numbers: yes, there will be database identifiers for the requests and we can show them in the requests overview page.

Registered as Redmine issue: 47496
https://code.pictura-dp.nl/issues/47496

**Comment by HMHardy** [comment]
I can live with requesters rather than proposers, but I would still like 'request type' amended to 'proposal name' - assuming this is where the name is created/captured? This will be more in line with ideas call vocabulary and I believe is also more self-explanatory.

**Comment by cannedit** [comment]
Hmmm, I think changing the (already agreed upon term) only here will cause confusion ...

**Comment by HMHardy** [comment]
I think requesters was agreed terminology for wider ELViS use but it was never really discussed in the context of VA and the ideas call used proposers. In any case as I said we can live with requesters but we must have a proposal or project name field - if you want this could be 'request name' rather than 'request type'? But I still think 'proposal name' is clearer and not inconsistent with being a requester. Happy to see what others say if anyone else comments.

**Comment by Karin-Wiltschke** [comment]
We are a little confused too, as we do not find things already useful in the ideas call in the provided template
eg.
corresponding proposer (requester)
additional Proposer (requester)

primary contact (email)

[VA proposal online draft_page 1_participant.pdf](https://github.com/DiSSCo/ELViS/files/4199127/VA.proposal.online.draft_page.1_participant.pdf)

**Comment by cannedit** [comment]
See my last remark in Github issue https://github.com/DiSSCo/ELViS/issues/36 and I add to this here: we have decided to not just put up a temporarily system for the VA Call, so just any system we can't re-use again later, but instead already create a solid basis for the Full ELViS, in order to already have something tangible to work on any further together after the 20th of February, so please, please, bear with us, this is a work in progress
