### ISSUE TITLE
requests linked with requester

### ISSUE THREAD

**Issue by Karin-Wiltschke** [DiSSCo/ELViS#40]
How is a request connected to a requester?
How does the VA coordinator know who made the request?

http://elvis-accept.pictura-hosting.nl/requests

in this page next to the titel should the Name  of the requester(s)

the same for 
http://elvis-accept.pictura-hosting.nl/requesters - the Project title should be mentioned (link)

**Comment by cannedit** [comment]
This is known in the back-end database, but I will register putting the name of the requester next to the title of a request in the requests overview page as a eature; the VA Coordinator will know which requester is connected to which request, because this is also stored in the database as a connection between his/her institution and the requests.

As for putting the project (request) titles next to the requesters; this is not in scope for now, so we will discuss later on whether this is necessary/feasible.
Registered as Redmine issue 47496
https://code.pictura-dp.nl/issues/47496
