### ISSUE TITLE
Institutions page

### ISSUE THREAD

**Issue by HMHardy** [DiSSCo/ELViS#43]
#### Description
As commented on 'people involved' issues this needs to distinguish digitising institutions from proposers - even if this page is just for the former it should say 'digitising institutions' in the heading and throughout.

It's not clear what the 'further details' field under collections is for? Although if the other fields above will be drop downs in due course then further details is fine.

Text 'Provide information on the "Process, workflow, facilities and outputs"' is confusing - I see this is taken from a heading in the ideas call form but since you have changed the order of the form it is no longer meaningful? at least not without more fields beneath it i.e. those in the next section. I would suggest deleting this text and moving the data box into the next section below workflows. This section could then be headed 'Facilities, workflow and outputs'. These sections are likely to require coordinator input.

You have a typo 'workFlow' for 'workflow' (proposed workflow field)

I will create a separate issue for the data release fields.

#### Steps to reproduce the issue

1.  
2. 
3. 

#### What's the expected result?

-

#### What's the actual result?

-

**Comment by cannedit** [comment]
I don't think changing "institutions" into "digitising institutions" is useful, because this is about a VA Call which is about digitising only, right?

Regarding "Further details", Ok, this will be more useful later on, when we add dropdown lists, but this will be for beyond the MVP ELViS, so we will leave this as is for now.

The text "Provide information, etc." will be deleted and he typo "workFlow" will be corrected, but I don't think moving the box for data and/or metadata fields is necessary, after all this is more directly related to the collections info than the other info below.

Text change and typo correction registered as Redmine ticket: 47510
https://code.pictura-dp.nl/issues/47510

**Comment by HMHardy** [comment]
It's useful because it is the terminology from the ideas call and will help people understand the distinction between requestors (who are part of an institution themselves) and the digitising institutions who are Synth members and listed in the drop down.

The metadata box is related to the workflow? However I can live with it staying where it is if the text above is deleted.

**Comment by cannedit** [comment]
Ok, the text will be deleted and the typo will be corrected.

**Comment by cannedit** [comment]
I discussed the comments about "digitising institutions" in this issue with the team and we decided to add a possibility to indicate what 'role' the institutions involved will have, by adding a set of so called radio buttons:
![VAcall_Institutions_Role](https://user-images.githubusercontent.com/22167327/74531758-da21eb00-4f2d-11ea-85cc-f304a6d5dea8.png)

**Comment by HMHardy** [comment]
Sorry Wim this sounds like a good plan but those categories don't make sense - There are either digtiising institutions (the 19 who hold collections and are part of VA), OR there are proposers/requesters who are generally part of research institutions, which may include various types of institutions but the type is not relevant, we just want to know who they are (i.e. per the ideas call, the proposer and their institution / contact details)

**Comment by wouteraddink** [comment]
A redesign needs more thought, suggestion to leave it as is for now. The issue seems about the **institute page** http://elvis-accept.pictura-hosting.nl/institutions **not** about the webform. Suggestion to leave that page also as is for now. This is for all institutions in Synth (and later DiSSCo) providing ELViS services not only VA. Not intended for requester affiliations. Needs more thought also how to make that clear in the future.

**Comment by cannedit** [comment]
Sorry, but this change is all we can do for now and it reflects more the way in which the form for the preparation of the VA call was asking for input. 
Furthermore I have not been informed that it was in scope for ELViS (MVP and FULL) that more institutions (more than the 19/20 that are in the dropdown menu now) should be able to participate. On the contrary: when I assumed that in the end (FULL ELViS) this should be the case, I got as a reaction: not within the life time of this project ...

**Comment by cannedit** [comment]
Sorry, we have put a lot of thought and work again in trying to deal with this confusion on the specs, so I need to know asap whether we go for this or not ...

**Comment by HMHardy** [comment]
I have been thinking about this. If the people involved page text has been changed to request details of other proposers, including their institutional affiliation (which ideally would not be in a free text box but that may be all we can do just now?), then the institutes page can be just for digitising institutions and can remain unchanged from the original. I would still prefer that it says 'digitising institutions' because this is then crystal clear to everyone involved, otherwise it is not clear whether they are being asked for more detail of their own institution etc. 
Hope that is helpful. The choices (radio buttons) was a good idea but doesn't work in practice at this stage because the categories are not right.

**Comment by wouteraddink** [comment]
To summarize the conclusion is not to go for the radio buttons and leave it as is. Institutes page needs a more informative title, I think we have to postpone this until after the mvp unless it can easily be changed to "dIgitising institutions" . However that would be temporary as it will rather need to be something like service providing institutions (providing not only digitization but also loans and visits services).

Regarding the number of providing institutions: all partners in Synth are in scope. That are the ones in VA plus the ones that are only in TA. That is at least one extra (Naturalis) I don't have the list here I am travelling. More are indeed not in scope during the Synth Plus project, but will be after handover to dissco. Might be however that we ( in mutual agreement) decide to allow extra institutes already earlier somewhere towards the end of the project if it has low impact on the project and clear benefits for adoption.

**Comment by cannedit** [comment]
@HMHardy and @wouteraddink sorry, but I think you are talking about two different things: @HMHardy about the request form and how institutions are labelled over there and @wouteraddink about the general overview page with the list of institutions

@HMHardy if we leave out the radio buttons, then I don't see the point on insisting on changing the label from "institutions" to "digitising institutions", because this is only meant for the VA call which is (for now) only about digitisation requests; besides: if you rename "institutions" into "digitising institutions" then that will be confusing, because as I understand from the form (and output) of the preparation for the VA call you can mention institutions which digitise and institutions which provide collections for digitisation and they don't necessarily have to be the same or do both activities; so where does that leave institutions that only offer collections and are not going to digitise themselves? That was the issue or rather the correction based on the form of the preparation of the VA call I intended to implement.

@wouteraddink the same argument for the current overview page "Institutions": for the moment those are the institutions involved only in this VA call, whether they digitise or not and offer collections or not, so no need to specify this in more detail.

Ok, long story short: 

- we keep the "People involved"-section in, but with another label and with - still - a free text field:
![ELViS_PeopleInvolved](https://user-images.githubusercontent.com/22167327/74567334-d87c1580-4f75-11ea-84ed-04354709a8bf.png)

- we will leave out the radio buttons for Institution Type

- we will maintain the title for the page "Institutions" as it is now (and do some other fine-tuning over there: order the list alphabetically and link the names of the institutions to a detail page on which there is more info, including the link to their CETAF page):
![ELViS_Institutions1](https://user-images.githubusercontent.com/22167327/74567355-e3cf4100-4f75-11ea-9cc2-c59fe1cc2724.png)
![ELVis_Institutions2](https://user-images.githubusercontent.com/22167327/74567363-e6ca3180-4f75-11ea-8768-6c27d0bede0a.png)

Note: the functionality in the screenshots shown here is already implemented on the current version which will be deployed on Accept for test on Monday
