### ISSUE TITLE
Data storage and release fields

### ISSUE THREAD

**Issue by HMHardy** [DiSSCo/ELViS#44]
#### Description
On the institutions involved page, the data storage and release fields have a few issues:

1. 'Name of a Platform' - Please amend to 'Platform for public data release'. 
Probably not possible to restrict this to a list at present but guidance will specify that this should be an established, free and open public platform such as GBIF. 
Are you expecting to have any field-level guidance? Or to provide links to overall guidance text elsewhere?

2. 'Collections Management System used' - please amend to 'Data Storage system(s) e.g. Collections Management and/or Media Asset Management systems' and allow for multiple entries
[this is not critical to this call but useful - to reassure panel that data will be appropriately stored and served to the public platforms above]

#### Steps to reproduce the issue

1.  
2. 
3. 

#### What's the expected result?

-

#### What's the actual result?

-

**Comment by cannedit** [comment]
I will change the texts for the two labels as mentioned.

Registered as Redmine issue: 47505
https://code.pictura-dp.nl/issues/47505

As for making the second mentioned text field repeatable, let's do this in the versions beyond the MVP ELViS, because then this whole section might be switched to the responsibility of the VA Coordinators anyway, given the discussions before about this.

The same goes for field-level guidance and help texts (we already agreed we would not do that in this version) unless it's about providing a simple link to information that can be found elsewhere.

**Comment by HMHardy** [comment]
OK thanks
