### ISSUE TITLE
Adding more institutes - repetition of information

### ISSUE THREAD

**Issue by emhaston** [DiSSCo/ELViS#88]
#### Description

When I add the first institute I entered the information relating to the project and the Facilities and workflow. Each time I entered a new institute I had to re-enter all the Facilities and workflow information. I couldn't copy and paste without having to go back into the first record and copying across each section separately which was a slow process. If there are a number of institutes included in the proposal then this would be a substantial issue.

#### Steps to reproduce the issue

1.  Create a new request
2. Add an institute and the Facilities and workflow proposed for that collection
3. Add a new institute and start adding the Facilities and workflow proposed for this next collection

#### What's the expected result?
- I would want the option of either copying across the information for the first institute entered or to enter the information from scratch.

#### What's the actual result?

- I have to enter the information from scratch for each institute.

#### Additional details / screenshot

https://elvis-accept.pictura-hosting.nl/requests/ca2eb99c-76d6-49cd-a103-f2e1200f1681

**Comment by wouteraddink** [comment]
Facilities and workflow may be different for each institution. So I'd rather improve by a replacing some of the open text fields by select options than by adding copy past options to repeat facilities and workflows for institutions.

**Comment by emhaston** [comment]
I agree with using more drop downs. I was going to create a couple of issues for these, particularly "Request Subject" and "Preservation Type", but they could also be useful for "Facilities Required".

**Comment by cannedit** [comment]
About the issue as originally registered:
the idea is that this information can be different per institution, so that's why it's not very useful to pass this on to another institution to be added; however, once you have provided the info for one insitution you can copy/paste it easily.
As for the requests for adding dropdowns: sure: if you can come up with generally applicable values for the dropdowns then we can implement this, but please then create another ticket for that.
