### ISSUE TITLE
Search field for institutions does not work 

### ISSUE THREAD

**Issue by mhirschfeld** [DiSSCo/ELViS#97]
#### Description
I cannot search for institutions / names not searchable

#### Steps to reproduce the issue

1.  Go on https://elvis-accept.pictura-hosting.nl/institutions
2.  Click in search field
3.  type a name

#### What's the expected result?

- list of institutions containing the word should appear

#### What's the actual result?

- nothing happens

**Comment by cannedit** [comment]
That functionality is not implemented yet.

**Comment by cannedit** [comment]
This has been taken care of in the ELViS version 0.6.0, released on the Acceptance server on 15/01/2021.

**Comment by B-San-Chi** [comment]
It is not entirely resolved.
for example: search by "garden" is correct and a list with all the institutions in all languages appears
But if you search by city "Berlin", two results appear, which is correct, but if you search for "Madrid" only one appears, and if you search for "Budapest" none appears.
By country nothing comes out

**Comment by cannedit** [comment]
Actually the seach is only working for key words in the name of the institution at the moment, so not for further items of it, like the city which is only in the address; in that sense only the two results for Berlin are wrong: there should only be one result. However, there is still a Github issue which asks for changing the name of the "Museum fur Naturkunde" into "Museum fur Naturkunde Berlin", so the "Berlin" for that search result might already be available 'under the hood'. In the next release we intend to make the name of an instution also editable for an Institution Moderator, so then there is no need for us anymore to take care of these kind of changes 'under the hood', so that will probably avoid these kind of issues.

**Comment by B-San-Chi** [comment]
ok. Thank you. But I think it could be interesting also search by city name for people who doesn't know if there are more than one institution that may interest them. Sorry, I'm looking with the eyes of someone who has two institutions in our city.

**Comment by cannedit** [comment]
I understand, but we only have 2 pages with institutions at the moment, so going over them manually is not a big deal for now, and there's still so much we have to take care of in order to meet the deadline, so we have to make choices. 

Workaround: when the functionality for editing the name of an institution becomes available, you can choose to add "(Madrid)" to the name of the other institution, so it can be searched for via "Madrid" also.

**Comment by B-San-Chi** [comment]
I will, thank you. I understand the priorities
